version: '3.8'
services:

  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    dns: 1.1.1.1
    user: ${XID:-1000}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ${PRIMARY_MOUNT}/data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CREATE_TUN_DEVICE=true
      - "OPENVPN_PROVIDER=${OPENVPN_PROVIDER}"
      - "OPENVPN_USERNAME=${TORRENT_USERNAME}"
      - "OPENVPN_PASSWORD=${TORRENT_PASSWORD}"
      - "TRANSMISSION_UMASK=0"
      - "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"
      - LOCAL_NETWORK=${LOCAL_NETWORK}

  transmission_proxy:
    image: haugene/transmission-openvpn-proxy:latest
    container_name: transmission_proxy
    restart: always
    ports:
      - "9091:8080"
    depends_on:
      - transmission

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    command: --schedule "0 0 */6 * * *"
    volumes:
      - ${SOCK_PATH}:/var/run/docker.sock
      - "${PRIMARY_MOUNT}/watchtower/config/:/config"
      - "${PRIMARY_MOUNT}/watchtower/docker-config.json:/config.json"
